name: Documentation
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxt6 libxrender1 libxext6 libgl1-mesa-glx libqt5widgets5 
          julia --color=yes --project=docs/ -e '
            using Pkg; 
            Pkg.develop(PackageSpec(path=pwd())); 
            Pkg.instantiate()'
      - name: Build and deploy
        env:
          GKSwstype: 100  # For GR plots
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --color=yes --project=docs/ docs/make.jl